name: Torela
url: https://torela.ee
api: https://torela.codeborne.com
permalink: /:year/:month/:title.html
ga: UA-134441911-1
email: tore@torela.ee
address: Ristiku 12, Tallinn
phone1: 5695 5722
iban: EE477700771003581431
