name: Torela
url: https://torela.ee
permalink: /:year/:month/:title.html
ga: UA-134441911-1
email: tore@torela.ee
address: Ristiku 12, Tallinn
phone1: 5695 5722
phone2: 5908 1914
iban: EE477700771003581431
