name: Torela
url: https://torela.ee
permalink: /:year/:month/:title.html
ga: UA-134441911-1
email: tore@torela.ee
address: Ristiku 12, Tallinn
phone1: 5333 1601
phone2: 5919 9336
iban: EE477700771003581431
