version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - /var/lib/mongodb-torela:/data/db
      - /var/lib/mongodb-torela-configdb:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: torela
      MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD}

  torela:
    build: .
    restart: always
    environment:
      - PASSWORD
    networks:
      - proxy
      - default

#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: torela
#      ME_CONFIG_MONGODB_ADMINPASSWORD: ${PASSWORD}

networks:
  proxy:
    external: true
